name: Branch Setup
on:
  push:
    branches: [ major-next-staging, lts-next-staging, major-next-develop ]

concurrency:
  group: ${{github.workflow}}-${{github.sha}}
  queue: single
  cancel-in-progress: false

jobs:
  setup:
    name: Create missing branches
    if: ${{ github.repository == vars.REPO_MAIN }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v5
      - name: Setup git client
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: Create central release staging branches if absent
        shell: bash
        run: |
          # Get major version
          version="$(cat package.json | jq '."version"' -r)"
          prettyversion="$(cat package.json | jq '."version-pretty"' -r)"
          majorversion="$(cat package.json | jq '."major-version"' -r)"

          # Check if branches exist
          if ! git rev-parse "origin/major-next" &>/dev/null; then
              # Create missing branches
              echo "Creating missing release staging branches..."
              echo "Creating pusher commit avoiding workflow runs..."
              git commit --allow-empty -m "[skip ci] Create missing release staging branches" || exit 1
              git push || exit 1
              if ! git rev-parse "origin/major-next-develop" &>/dev/null; then
                   echo "Creating missing develop build release staging branches..."
                   git checkout -b "major-next-develop" || exit 1
                   git push --set-upstream origin "major-next-develop" || exit 1
              fi
              if ! git rev-parse "origin/major-next-testing" &>/dev/null; then
                   echo "Creating missing testing build release staging branches..."
                   git checkout -b "major-next-testing" || exit 1
                   git push --set-upstream origin "major-next-testing" || exit 1
              fi
              if ! git rev-parse "origin/major-next-staging" &>/dev/null; then
                   echo "Creating missing staging build release staging branches..."
                   git checkout -b "major-next-staging" || exit 1
                   git push --set-upstream origin "major-next-staging" || exit 1
              fi
              if ! git rev-parse "origin/major-next-experimental" &>/dev/null; then
                   echo "Creating missing experimental build release staging branches..."
                   git checkout -b "major-next-experimental" || exit 1
                   git push --set-upstream origin "major-next-experimental" || exit 1
              fi
              if ! git rev-parse "origin/major-next" &>/dev/null; then
                   echo "Creating missing stable build release staging branches..."
                   git checkout -b "major-next" || exit 1
                   git push --set-upstream origin "major-next" || exit 1
              fi
              echo Done.
          else
              # No branches to create
              echo "Branches for release staging already exist, skipped"
          fi
      - name: Create major build branches if absent
        if: ${{ github.ref_name == 'major-next-staging' }}
        shell: bash
        run: |
          # Get major version
          version="$(cat package.json | jq '."version"' -r)"
          prettyversion="$(cat package.json | jq '."version-pretty"' -r)"
          majorversion="$(cat package.json | jq '."major-version"' -r)"

          # Check if branches exist
          if ! git rev-parse "origin/major-$majorversion" &>/dev/null; then
              # Create missing branches
              echo "Creating missing branches for $majorversion..."
              echo "Creating pusher commit avoiding workflow runs..."
              git commit --allow-empty -m "[skip ci] Create missing major build branches" || exit 1
              git push || exit 1
              echo "Creating missing develop branch for $majorversion..."
              git checkout -b "major-$majorversion-develop" || exit 1
              git push --set-upstream origin "major-$majorversion-develop" || exit 1
              echo "Creating missing testing branch for $majorversion..."
              git checkout -b "major-$majorversion-testing" || exit 1
              git push --set-upstream origin "major-$majorversion-testing" || exit 1
              echo "Creating missing staging branch for $majorversion..."
              git checkout -b "major-$majorversion-staging" || exit 1
              git push --set-upstream origin "major-$majorversion-staging" || exit 1
              echo "Creating missing experimental branch for $majorversion..."
              git checkout -b "major-$majorversion-experimental" || exit 1
              git push --set-upstream origin "major-$majorversion-experimental" || exit 1
              echo "Creating missing stable branch for $majorversion..."
              git checkout -b "major-$majorversion" || exit 1
              git push --set-upstream origin "major-$majorversion" || exit 1
              echo Done.
          else
              # No branches to create
              echo "Branches for $majorversion already exist, skipped"
          fi
