name: Checks
on:
  push:
  pull_request_target:
    types: [synchronize]
permissions:
  contents: write

jobs:
  checks:
    name: Merge conflict checks
    runs-on: ubuntu-latest
    steps:
      - name: Check if PRs have conflicts
        uses: eps1lon/actions-label-merge-conflict@v3
        if: github.repository == ${{ vars.REPO_MAIN }}
        with:
          dirtyLabel: "merge-conflicts"
          repoToken: "${{ secrets.MERGE_CONFLICT_LABEL_PAT }}"

  compiletest:
    name: Attempt build
    strategy:
      fail-fast: false
      matrix:
        arch: [x64, arm64]
        os:
          # FIXME: macos cannot be built at this moment
          # - name: macos
          #   image: macos-latest
          #   shell: bash
          #   forge_platform: darwin
          - name: linux
            image: ubuntu-22.04
            shell: bash
            forge_platform: linux
          - name: windows
            image: windows-latest
            shell: cmd
            forge_platform: win32

    runs-on: ${{ matrix.os.image }}
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4

      - name: Set up node & dependencies
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - uses: nrwl/nx-set-shas@v4

      - name: Update build info
        shell: ${{ matrix.os.shell }}
        run: npm run chore:update-build-info

      - name: Attempt server build
        shell: ${{ matrix.os.shell }}
        run: pnpm exec nx run server:build
