name: Checks
on:
  push:
  pull_request_target:
    types: [synchronize]
permissions:
  contents: write

jobs:
  checks:
    name: Merge conflict checks
    runs-on: ubuntu-latest
    steps:
      - name: Check if PRs have conflicts
        uses: eps1lon/actions-label-merge-conflict@v3
        if: github.repository == ${{ vars.REPO_MAIN }}
        with:
          dirtyLabel: "merge-conflicts"
          repoToken: "${{ secrets.MERGE_CONFLICT_LABEL_PAT }}"
  compileattempt:
    name: Attempt build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4

      - name: Set up node & dependencies
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - uses: nrwl/nx-set-shas@v4

      - name: Update build info
        run: npm run chore:update-build-info

      - name: Attempt server build
        run: pnpm exec nx run server:build
